# Databricks notebook source
# MAGIC %md ### Prep (read instructions below)

# COMMAND ----------

# MAGIC %run ../functions/utility

# COMMAND ----------

# Reset widgets
dbutils.widgets.removeAll()

# COMMAND ----------

settings = build_dictionary("settings")
pipelines = list(settings["pipelines"].keys())

# COMMAND ----------

# Drop-down for pipeline
dbutils.widgets.dropdown(
    name="pipeline",
    defaultValue="",
    choices=[ "" ] + pipelines
)

# COMMAND ----------

dbutils.notebook.exit("Stop here.")

# COMMAND ----------

# MAGIC %md
# MAGIC
# MAGIC # Reset/Rebuild silver environment
# MAGIC
# MAGIC ## Instructions
# MAGIC
# MAGIC 1. Clear state & outputs (Escape, 0, 0, Enter).
# MAGIC 1. Run all above this cell (Select this cell & press Shift-Alt-Up).
# MAGIC 1. Choose a pipeline.
# MAGIC 1. Run all below this cell (Select this cell & press Shift-Alt-Down).
# MAGIC
# MAGIC ## WARNING
# MAGIC
# MAGIC Run this if you want to reset silver from scratch.
# MAGIC
# MAGIC * drop **ALL** silver tables
# MAGIC * delete **EVERYTHING** in the utility folder
# MAGIC * **DEEP CLONE** silver tables from DMS or other schema
# MAGIC * In some cases, add an incrementing id column (if you need something else, code it out below)

# COMMAND ----------

# Variables
catalog                         = spark.catalog.currentCatalog()
pipeline                        = dbutils.widgets.get("pipeline")
this_pipeline                   = settings["pipelines"][pipeline]
silver_schema_name              = this_pipeline["silver_schema_name"]
dms_schema_name                 = this_pipeline["dms_schema_name"]
tables_in_dms                   = this_pipeline["silver"]["tables_in_dms"]
tables_not_in_dms               = this_pipeline["silver"]["tables_not_in_dms"]
all_tables_with_custom_types    = this_pipeline["silver"]["all_tables_with_custom_types"]
identity_columns                = this_pipeline["silver"]["identity_columns"]

# COMMAND ----------

import re
from textwrap import dedent

# Delete everything under utility folder
folders = getCmd(f"find /Volumes/{catalog}/{silver_schema_name}/utility -mindepth 1 -maxdepth 1").split('\n')
for folder in folders:
    if folder:
        print(folder)
        dbutils.fs.rm(folder, recurse=True)

for table_name in tables_in_dms:
    # Variables
    df = spark.table(f"{dms_schema_name}.{table_name}")
    fields = {field.name: field.dataType for field in df.schema.fields}

    # Get the command to create the dms table
    create_table_statement = spark.sql(f"show create table {dms_schema_name}.{table_name}").collect()[0][0]

    # Update "id" to auto-increment
    # Need to update this next time I have any identity columns
    for col in identity_columns:
        if col in fields.keys():
            max_id = spark.sql(f"select max({col}) as max_id from {dms_schema_name}.{table_name}").collect()[0][f"max_id"]
            create_table_statement = re.sub(r"^\s*" + col + r"\s+INT,.*$",
                                f"  {col} bigint generated by default as identity (start with {max_id + 1} increment by 1),",
                                create_table_statement,
                                flags=re.MULTILINE
                                )

    # SQL statements
    sql_commands = dedent(f"""
                            drop table if exists {catalog}.{silver_schema_name}.{table_name};
                            {create_table_statement.replace(dms_schema_name, silver_schema_name) + ";"}

                            alter table {catalog}.{silver_schema_name}.{table_name} set tblproperties ('delta.columnMapping.mode' = 'name');
                            alter table {catalog}.{silver_schema_name}.{table_name} drop column dms_extract_time;

                            insert into {catalog}.{silver_schema_name}.{table_name}
                            select *
                                except (dms_extract_time)
                            from {catalog}.{dms_schema_name}.{table_name};

                            alter table {silver_schema_name}.{table_name} add column source_metadata STRUCT<
                                file_path: STRING,
                                file_name: STRING,
                                file_size: BIGINT,
                                file_block_start: BIGINT,
                                file_block_length: BIGINT,
                                file_modification_time: TIMESTAMP
                            >;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN file_path STRING;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN file_modification_time TIMESTAMP;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN pk_columns_checksum STRING;
                            alter table {catalog}.{silver_schema_name}.{table_name} SET OWNER TO admins;
                            """).strip("\n")

    run_sql_commands(sql_commands)

# Just does a cast() on columns with custom types
# Code needs to be customized e.g. change or remove the regexp_replace
for table_with_custom_types in all_tables_with_custom_types:
    # Variables
    table_name = table_with_custom_types["table_name"]
    column_names = [c["name"] for c in table_with_custom_types["columns"]]
    data_types = [c["type"] for c in table_with_custom_types["columns"]]
    custom_columns = ", ".join(column_names)
    expression_list = []
    for column_name, data_type in zip(column_names, data_types):
        expression_list.append(f" CAST(regexp_replace({column_name},'[$,]','') AS {data_type}) AS {column_name}")
    custom_columns_cast_expr = ",\n".join(expression_list)

    # SQL statements
    sql_commands = dedent(f"""
                            drop table if exists {catalog}.{silver_schema_name}.{table_name};

                            create table {catalog}.{silver_schema_name}.{table_name}
                            using delta
                            as
                            select * except (dms_extract_time, {custom_columns}),
                                {custom_columns_cast_expr}
                            from {catalog}.{dms_schema_name}.{table_name};

                            alter table {catalog}.{silver_schema_name}.{table_name} set tblproperties ('delta.columnMapping.mode' = 'name');

                            alter table {silver_schema_name}.{table_name} add column source_metadata STRUCT<
                                file_path: STRING,
                                file_name: STRING,
                                file_size: BIGINT,
                                file_block_start: BIGINT,
                                file_block_length: BIGINT,
                                file_modification_time: TIMESTAMP
                            >;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN file_path STRING;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN file_modification_time TIMESTAMP;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN pk_columns_checksum STRING;
                            alter table {catalog}.{silver_schema_name}.{table_name} SET OWNER TO admins;
                            """).strip("\n")

    run_sql_commands(sql_commands)

for table_name in tables_not_in_dms:
    # SQL statements
    sql_commands = dedent(f"""
                            drop table if exists {catalog}.{silver_schema_name}.{table_name};
                            CREATE TABLE IF NOT EXISTS {catalog}.{silver_schema_name}.{table_name};

                            alter table {catalog}.{silver_schema_name}.{table_name} set tblproperties ('delta.columnMapping.mode' = 'name');

                            alter table {silver_schema_name}.{table_name} add column source_metadata STRUCT<
                                file_path: STRING,
                                file_name: STRING,
                                file_size: BIGINT,
                                file_block_start: BIGINT,
                                file_block_length: BIGINT,
                                file_modification_time: TIMESTAMP
                            >;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN file_path STRING;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN file_modification_time TIMESTAMP;
                            alter table {catalog}.{silver_schema_name}.{table_name} ADD COLUMN pk_columns_checksum STRING;
                            alter table {catalog}.{silver_schema_name}.{table_name} SET OWNER TO admins;
                            """).strip("\n")

    run_sql_commands(sql_commands)